console.log("settings imported");
const BorderColor = "lime";
const OutlineColor = "black";
const BackgroundColor = "green";
const CellHeight = 30;
const CellWidth = 30;
const BorderSize = 0;
const OutlineSize = 10;
const Columns = 9;
const Rows = 9;
const TicksPerSec = 4;
const dev = false;